export interface Course {
  id: number;
  skillSlug: string;
  title: string;
  image: string;
  instructor: string;
  rating: number;
  level: "Beginner" | "Intermediate" | "Advanced";
  peopleImage: string;
  lessons: number;
  hours: number;
  minutes: number;
  comments: number;
  price: number;
  duration: string;
}

export const courses: Course[] = [
  {
    id: 1,
    skillSlug: "featured",
    title: "Learn Figma from Basic",
    image: "/course1.png",
    instructor: "purepearl studio",
    rating: 4.5,
    level: "Beginner",
    peopleImage: "/peoples.png",
    lessons: 17,
    hours: 8,
    minutes: 30,
    comments: 124,
    price: 25,
    duration: "lifetime",
  },
  {
    id: 2,
    skillSlug: "featured",
    title: "Master UI/UX Design",
    image: "/course2.png",
    instructor: "Design Academy",
    rating: 4.8,
    level: "Intermediate",
    peopleImage: "/peoples.png",
    lessons: 24,
    hours: 12,
    minutes: 30,
    comments: 186,
    price: 35,
    duration: "lifetime",
  },
  {
    id: 3,
    skillSlug: "featured",
    title: "Creative Design Fundamentals",
    image: "/course3.png",
    instructor: "Creative Studio",
    rating: 4.6,
    level: "Beginner",
    peopleImage: "/peoples.png",
    lessons: 15,
    hours: 7,
    minutes: 30,
    comments: 98,
    price: 20,
    duration: "lifetime",
  },
  {
    id: 4,
    skillSlug: "music",
    title: "Music Production for Beginners",
    image: "/course4.png",
    instructor: "Sound Lab",
    rating: 4.7,
    level: "Beginner",
    peopleImage: "/peoples.png",
    lessons: 20,
    hours: 10,
    minutes: 30,
    comments: 142,
    price: 30,
    duration: "lifetime",
  },
  {
    id: 5,
    skillSlug: "music",
    title: "Learn Piano from Scratch",
    image: "/course5.png",
    instructor: "Music Academy",
    rating: 4.5,
    level: "Beginner",
    peopleImage: "/peoples.png",
    lessons: 18,
    hours: 9,
    minutes: 30,
    comments: 115,
    price: 28,
    duration: "lifetime",
  },
  {
    id: 6,
    skillSlug: "drawing-painting",
    title: "Digital Drawing Masterclass",
    image: "/course6.png",
    instructor: "Art House",
    rating: 4.9,
    level: "Intermediate",
    peopleImage: "/peoples.png",
    lessons: 28,
    hours: 14,
    minutes: 30,
    comments: 210,
    price: 32,
    duration: "lifetime",
  },
  {
    id: 7,
    skillSlug: "drawing-painting",
    title: "Watercolor Painting Basics",
    image: "/course1.png",
    instructor: "Creative Canvas",
    rating: 4.6,
    level: "Beginner",
    peopleImage: "/peoples.png",
    lessons: 16,
    hours: 8,
    minutes: 30,
    comments: 87,
    price: 22,
    duration: "lifetime",
  },
  {
    id: 8,
    skillSlug: "marketing",
    title: "Digital Marketing Essentials",
    image: "/course2.png",
    instructor: "Marketing Pro",
    rating: 4.8,
    level: "Beginner",
    peopleImage: "/peoples.png",
    lessons: 22,
    hours: 11,
    minutes: 30,
    comments: 175,
    price: 29,
    duration: "lifetime",
  },
  {
    id: 9,
    skillSlug: "marketing",
    title: "Growth Marketing Strategy",
    image: "/course3.png",
    instructor: "Growth Lab",
    rating: 4.7,
    level: "Advanced",
    peopleImage: "/peoples.png",
    lessons: 30,
    hours: 16,
    minutes: 30,
    comments: 230,
    price: 40,
    duration: "lifetime",
  },
  {
    id: 10,
    skillSlug: "animation",
    title: "2D Animation Fundamentals",
    image: "/course4.png",
    instructor: "Motion Studio",
    rating: 4.6,
    level: "Beginner",
    peopleImage: "/peoples.png",
    lessons: 19,
    hours: 10,
    minutes: 30,
    comments: 126,
    price: 35,
    duration: "lifetime",
  },
  {
    id: 11,
    skillSlug: "social-media",
    title: "Social Media Content Creation",
    image: "/course5.png",
    instructor: "Creator Hub",
    rating: 4.5,
    level: "Beginner",
    peopleImage: "/peoples.png",
    lessons: 14,
    hours: 6,
    minutes: 30,
    comments: 94,
    price: 24,
    duration: "lifetime",
  },
  {
    id: 12,
    skillSlug: "ui-ux-design",
    title: "UI/UX Design Complete Guide",
    image: "/course6.png",
    instructor: "UX Studio",
    rating: 4.9,
    level: "Intermediate",
    peopleImage: "/peoples.png",
    lessons: 32,
    hours: 18,
    minutes: 30,
    comments: 285,
    price: 45,
    duration: "lifetime",
  },
  {
    id: 13,
    skillSlug: "ui-ux-design",
    title: "Figma UI Design Masterclass",
    image: "/course1.png",
    instructor: "Design Experts",
    rating: 4.8,
    level: "Intermediate",
    peopleImage: "/peoples.png",
    lessons: 26,
    hours: 13,
    minutes: 30,
    comments: 194,
    price: 38,
    duration: "lifetime",
  },
  {
    id: 14,
    skillSlug: "creative-marketing",
    title: "Creative Marketing Strategies",
    image: "/course2.png",
    instructor: "Brand Studio",
    rating: 4.7,
    level: "Intermediate",
    peopleImage: "/peoples.png",
    lessons: 21,
    hours: 10,
    minutes: 30,
    comments: 138,
    price: 32,
    duration: "lifetime",
  },
  {
    id: 15,
    skillSlug: "digital-illustration",
    title: "Digital Illustration from Zero",
    image: "/course3.png",
    instructor: "Illustration Lab",
    rating: 4.8,
    level: "Beginner",
    peopleImage: "/peoples.png",
    lessons: 18,
    hours: 9,
    minutes: 30,
    comments: 121,
    price: 27,
    duration: "lifetime",
  },
  {
    id: 16,
    skillSlug: "film-video",
    title: "Video Editing with Premiere Pro",
    image: "/course4.png",
    instructor: "Film Academy",
    rating: 4.7,
    level: "Intermediate",
    peopleImage: "/peoples.png",
    lessons: 27,
    hours: 15,
    minutes: 30,
    comments: 176,
    price: 35,
    duration: "lifetime",
  },
  {
    id: 17,
    skillSlug: "crafts",
    title: "Creative Crafts for Beginners",
    image: "/course5.png",
    instructor: "Craft Studio",
    rating: 4.5,
    level: "Beginner",
    peopleImage: "/peoples.png",
    lessons: 13,
    hours: 6,
    minutes: 30,
    comments: 72,
    price: 18,
    duration: "lifetime",
  },
  {
    id: 18,
    skillSlug: "freelance-entrepreneurship",
    title: "Start Your Freelancing Career",
    image: "/course6.png",
    instructor: "Freelance Academy",
    rating: 4.8,
    level: "Beginner",
    peopleImage: "/peoples.png",
    lessons: 25,
    hours: 12,
    minutes: 30,
    comments: 201,
    price: 25,
    duration: "lifetime",
  },
  {
    id: 19,
    skillSlug: "graphic-design",
    title: "Graphic Design Complete Course",
    image: "/course1.png",
    instructor: "Pixel Studio",
    rating: 4.9,
    level: "Intermediate",
    peopleImage: "/peoples.png",
    lessons: 29,
    hours: 15,
    minutes: 30,
    comments: 248,
    price: 40,
    duration: "lifetime",
  },
  {
    id: 20,
    skillSlug: "photography",
    title: "Photography Masterclass",
    image: "/course2.png",
    instructor: "Photo Academy",
    rating: 4.7,
    level: "Beginner",
    peopleImage: "/peoples.png",
    lessons: 23,
    hours: 11,
    minutes: 30,
    comments: 154,
    price: 30,
    duration: "lifetime",
  },
  {
    id: 21,
    skillSlug: "productivity",
    title: "Productivity & Time Management",
    image: "/course3.png",
    instructor: "Success Studio",
    rating: 4.6,
    level: "Beginner",
    peopleImage: "/peoples.png",
    lessons: 12,
    hours: 5,
    minutes: 30,
    comments: 89,
    price: 20,
    duration: "lifetime",
  },
  {
    id: 22,
    skillSlug: "web-development",
    title: "Modern Web Development",
    image: "/course4.png",
    instructor: "Code Academy",
    rating: 4.9,
    level: "Intermediate",
    peopleImage: "/peoples.png",
    lessons: 35,
    hours: 20,
    minutes: 30,
    comments: 315,
    price: 45,
    duration: "lifetime",
  },
  {
    id: 23,
    skillSlug: "web-development",
    title: "React & Next.js from Scratch",
    image: "/course5.png",
    instructor: "Frontend Masters",
    rating: 4.8,
    level: "Intermediate",
    peopleImage: "/peoples.png",
    lessons: 31,
    hours: 17,
    minutes: 30,
    comments: 267,
    price: 50,
    duration: "lifetime",
  },
  {
    id: 24,
    skillSlug: "data-science",
    title: "Data Science with Python",
    image: "/course6.png",
    instructor: "Data Academy",
    rating: 4.8,
    level: "Intermediate",
    peopleImage: "/peoples.png",
    lessons: 34,
    hours: 19,
    minutes: 30,
    comments: 292,
    price: 42,
    duration: "lifetime",
  },
  {
    id: 25,
    skillSlug: "cooking",
    title: "Cooking Fundamentals",
    image: "/course1.png",
    instructor: "Chef Studio",
    rating: 4.6,
    level: "Beginner",
    peopleImage: "/peoples.png",
    lessons: 16,
    hours: 7,
    minutes: 30,
    comments: 103,
    price: 22,
    duration: "lifetime",
  },
  {
    id: 26,
    skillSlug: "featured",
    title: "Learn Figma from Basic",
    image: "/course4.png",
    instructor: "purepearl studio",
    rating: 4.5,
    level: "Beginner",
    peopleImage: "/peoples.png",
    lessons: 17,
    hours: 8,
    minutes: 30,
    comments: 124,
    price: 25,
    duration: "lifetime",
  },
  {
    id: 27,
    skillSlug: "featured",
    title: "Master UI/UX Design",
    image: "/course5.png",
    instructor: "Design Academy",
    rating: 4.8,
    level: "Intermediate",
    peopleImage: "/peoples.png",
    lessons: 24,
    hours: 12,
    minutes: 30,
    comments: 186,
    price: 35,
    duration: "lifetime",
  },
  {
    id: 28,
    skillSlug: "featured",
    title: "Creative Design Fundamentals",
    image: "/course6.png",
    instructor: "Creative Studio",
    rating: 4.6,
    level: "Beginner",
    peopleImage: "/peoples.png",
    lessons: 15,
    hours: 7,
    minutes: 30,
    comments: 98,
    price: 20,
    duration: "lifetime",
  },
];
